global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'monitoring-system'
    static_configs:
      - targets: ['monitor:8000']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:5000']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s